object FrmRegistrasiPembelian: TFrmRegistrasiPembelian
  Left = 0
  Top = 0
  Caption = 'Registrasi Pembelian'
  ClientHeight = 682
  ClientWidth = 1239
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object No: TLabel
    Left = 24
    Top = 27
    Width = 103
    Height = 19
    Caption = 'No. Pembelian'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
  end
  object Label6: TLabel
    Left = 289
    Top = 29
    Width = 7
    Height = 20
    Caption = '-'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label2: TLabel
    Left = 289
    Top = 122
    Width = 7
    Height = 20
    Caption = '-'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label3: TLabel
    Left = 24
    Top = 72
    Width = 98
    Height = 19
    Caption = 'Kode Supplier'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
  end
  object Label4: TLabel
    Left = 24
    Top = 120
    Width = 57
    Height = 19
    Caption = 'Tanggal'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
  end
  object Panel1: TPanel
    Left = 464
    Top = 602
    Width = 761
    Height = 63
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object btnPreview: TLMDShapeButton
      Left = 377
      Top = 12
      Width = 100
      Height = 35
      Caption = 'Preview'
      ParentFont = False
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      AllowTransparency = True
      AllowMouseOver = True
      Shape.Brush.Color = clBtnFace
      Style = sbs3D
    end
    object btnPrint: TLMDShapeButton
      Left = 502
      Top = 12
      Width = 100
      Height = 35
      Caption = 'Print'
      ParentFont = False
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      AllowTransparency = True
      AllowMouseOver = True
      Shape.Brush.Color = clBtnFace
      Style = sbs3D
    end
    object btnClose: TBitBtn
      Left = 640
      Top = 12
      Width = 100
      Height = 35
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      Kind = bkClose
      NumGlyphs = 2
      ParentFont = False
      TabOrder = 0
      OnClick = btnCloseClick
    end
    object btnDelete: TBitBtn
      Left = 252
      Top = 12
      Width = 100
      Height = 35
      Caption = '&Delete'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      Kind = bkNo
      NumGlyphs = 2
      ParentFont = False
      TabOrder = 1
    end
    object btnEdit: TBitBtn
      Left = 130
      Top = 12
      Width = 100
      Height = 35
      Caption = '&Edit'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      Kind = bkHelp
      NumGlyphs = 2
      ParentFont = False
      TabOrder = 2
      OnClick = btnEditClick
    end
    object btnEntry: TBitBtn
      Left = 16
      Top = 12
      Width = 100
      Height = 35
      Caption = '&Entry'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      Kind = bkAll
      NumGlyphs = 2
      ParentFont = False
      TabOrder = 3
      OnClick = btnEntryClick
    end
  end
  object tabelTampilDataPembelian: TwwDBGrid
    Left = 24
    Top = 179
    Width = 1201
    Height = 417
    IniAttributes.Delimiter = ';;'
    IniAttributes.UnicodeIniFile = False
    TitleColor = clBtnFace
    FixedCols = 0
    ShowHorzScrollBar = True
    DataSource = TransaksiDataSource
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    TitleAlignment = taLeftJustify
    TitleFont.Charset = DEFAULT_CHARSET
    TitleFont.Color = clWindowText
    TitleFont.Height = -11
    TitleFont.Name = 'Tahoma'
    TitleFont.Style = []
    TitleLines = 1
    TitleButtons = False
  end
  object inputTanggalAwal: TwwDBDateTimePicker
    Left = 163
    Top = 117
    Width = 120
    Height = 27
    CalendarAttributes.Font.Charset = DEFAULT_CHARSET
    CalendarAttributes.Font.Color = clWindowText
    CalendarAttributes.Font.Height = -11
    CalendarAttributes.Font.Name = 'Tahoma'
    CalendarAttributes.Font.Style = []
    Epoch = 1950
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    ShowButton = True
    TabOrder = 2
  end
  object InputNoPembelianAwal: TEdit
    Left = 162
    Top = 24
    Width = 120
    Height = 27
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 3
  end
  object InputNoPembelianAkhir: TEdit
    Left = 302
    Top = 24
    Width = 120
    Height = 27
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 4
  end
  object inputTanggalAkhir: TwwDBDateTimePicker
    Left = 301
    Top = 117
    Width = 120
    Height = 27
    CalendarAttributes.Font.Charset = DEFAULT_CHARSET
    CalendarAttributes.Font.Color = clWindowText
    CalendarAttributes.Font.Height = -11
    CalendarAttributes.Font.Name = 'Tahoma'
    CalendarAttributes.Font.Style = []
    Epoch = 1950
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    ShowButton = True
    TabOrder = 5
  end
  object btnCari: TBitBtn
    Left = 302
    Top = 65
    Width = 87
    Height = 36
    Caption = '&Cari'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    Kind = bkHelp
    NumGlyphs = 2
    ParentFont = False
    TabOrder = 6
    OnClick = btnCariClick
  end
  object btnTampil: TBitBtn
    Left = 432
    Top = 106
    Width = 185
    Height = 50
    Caption = 'Tampil Data Transaksi'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 7
    OnClick = btnTampilClick
  end
  object inputKodeSupplier: TEdit
    Left = 162
    Top = 69
    Width = 120
    Height = 27
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 8
  end
  object TransaksiDataSource: TDataSource
    DataSet = QueryTransaksiPembelian
    Left = 752
    Top = 24
  end
  object QueryTransaksiPembelian: TFDQuery
    Connection = DM.FDConnection
    SQL.Strings = (
      'select A.*, B.Nama_Sup'
      'from Pembelian A inner join Supplier B'
      'on A.Kode_Sup = B.Kode_Sup')
    Left = 880
    Top = 24
  end
end
